args:
  latent_channels: 16
  mode: inference
  # load: "{your CogVideoX SAT folder}/transformer" # This is for Full model without lora adapter
  # load: "{your lora folder} such as zRzRzRzRzRzRzR/lora-disney-08-20-13-28" # This is for Full model without lora adapter
  # load: "/data/Dynamics/cogvideox-sat/2b/transformer"
  load: /data/Dynamics/cogvideox_lora_ckpts/lora_cogvidx5b_scalarflow_all_i2v_fix3samples-09-09-05-39/

  batch_size: 1
  input_type: txt
  input_file: configs/test_smoke.txt

  sdedit_strength: 0.75  # 'all'  # 0.0 to 1.0, 1.0 means full sampling
  sdedit_strength_fake: 0.5
  # sdedit_strength_min: 0.1
  # sdedit_strength_max: 0.61
  # sdedit_strength_step: 0.02
  sdedit_prompt_idx: 0
  # sdedit_is_zero123: False
  sdedit_labels_dir: /data/Dynamics/ScalarFlow_cogvideox_dataset/labels
  sdedit_sequence_name: sim_000000
  sdedit_frames_dir: /data/Dynamics/ScalarRealAnother
  sdedit_frames_dir_fake: /data/Dynamics/gaussian_fluid_dynamics_log/gaussian_pbd_fluid_scalar_another_simrec_simple/gpf_default_start20dur110step1_futsince110du60_fake0134_stren0d5_curiter250_emitr1d61/training_render_for_generative_cogvideox_unshift
  sdedit_prefix_start_idx: 121
  sdedit_prefix_start_idx_fake: 101
  sdedit_prefix_num_frames: 9
  sdedit_start_idx: 110
  sdedit_label_start_idx: 121
  sdedit_num_frames: 65
  sdedit_frame_step: 1
  # sdedit_zero123_use_ckp2: False
  # sdedit_zero123_use_ckp2_psnr: False
  sdedit_zero123_finetune_step: 15500
  sdedit_view_idx: 2
  sdedit_tgt_view_idx: 0
  # sdedit_view_start_idx: 0
  # sdedit_view_end_idx: 10
  sdedit_ignore_input_fps: True

  sampling_num_frames: 17  # Must be 13, 11 or 9
  sampling_fps: 8
  # fp16: True # For CogVideoX-2B
  bf16: True # For CogVideoX-5B
  output_dir: /data/Dynamics/cogvideox_lora_outputs_real_capture/5b_lora_all_sdedit_pi2v_future_scalar/
  force_inference: True
